version: "3"
services:
  chromedriver:
    image: selenium/standalone-chrome
    ports: 
      - "4444:4444"

  selenium_test:
    build: ./
    command: python app.py
    volumes:
      - ./:/app
    links:
      - chromedriver